language: cpp
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60 
  - sudo apt-get install -y -qq  libboost-test-dev libboost-system-dev libboost-program-options-dev
script:
  - cmake -H. -BBuild
  - cmake --build Build
  - cmake --build Build --target test
  - cmake --build Build --target package
  - netstat | grep 9001
  - cd Build/tests
  - ./test_server_cli  -t --log-level=all test_suite_main_1
  - ./test_server_cli  -t --log-level=all test_suite_main_2
  - ./test_server_cli  -t --log-level=all test_suite_main_3
  - cd ../../
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T Build/join_server-*.$TRAVIS_BUILD_NUMBER-Linux.deb -utatyana-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/tatyana-otus/hw_otus/join_server/$TRAVIS_BUILD_NUMBER/join_server-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 